### ISSUE TITLE
Markdown Preview BG color issue

### ISSUE THREAD

**Issue by ToxidoLiu** [arcticicestudio/nord-atom-ui#45]
When in the markdown preview, color of the bold text using both
`**test text**`
`__test text__`
is mixed with the editor's background color (see figure below)
![issue1](https://cloud.githubusercontent.com/assets/5713865/20552163/100cff76-b183-11e6-9955-98ba3c37b2b2.png)

thanks!

**Comment by arcticicestudio** [comment]
Thanks for your report, I was able to reproduce this bug and will release a APM package patch update.

**Comment by arcticicestudio** [comment]
Bold text is now colored correctly.

![ghi-45-scrot-fixed](https://cloud.githubusercontent.com/assets/7836623/20575493/ca7e7dae-b1b9-11e6-9fab-3e8baa3c4303.png)

**Comment by arcticicestudio** [comment]
I've released a APM package version [`0.8.1`](https://github.com/arcticicestudio/nord-atom-ui/releases/tag/v0.8.1) including the bugfix for this issue.
