### ISSUE TITLE
Folder background in tree-view

### ISSUE THREAD

**Issue by marza91** [arcticicestudio/nord-atom-ui#47]
Selected folders in tree view have a transparent background unlike files, which are highlighted. Is this intentional, or could it be changed? It makes it really hard to navigate the tree view using the keyboard.

I've removed these lines on my computer, which fixes the issue:
https://github.com/arcticicestudio/nord-atom-ui/blob/master/styles/tree-view.less#L61-L63

I can make a pull request if you're not against removing it.

**Comment by arcticicestudio** [comment]
Thansk for your report, that is indeed not the way a selected list item should be colored.
These lines of code were intended for something different, but I forgot to remove them.

I've fixed already fixed it some moments ago to include it in the next package update.

**Comment by arcticicestudio** [comment]
![ghi-47-scrot-after](https://cloud.githubusercontent.com/assets/7836623/20810298/89cd19ea-b809-11e6-9f5b-da198429df80.png)


![ghi-47-scrot-after](https://cloud.githubusercontent.com/assets/7836623/20810306/8d402f72-b809-11e6-8609-2339974c20d7.gif)

**Comment by arcticicestudio** [comment]
@marza91 Released a APM package update version [`0.9.0`](https://github.com/arcticicestudio/nord-atom-ui/releases/tag/v0.9.0) which includes the fix for this issue.

**Comment by marza91** [comment]
Updated and working, thanks a lot :)
