### ISSUE TITLE
Deprecated selector in `nord-atom-ui/index.less`

### ISSUE THREAD

**Issue by YogliB** [arcticicestudio/nord-atom-ui#51]
In `nord-atom-ui/index.less`: 
Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:
* `.project-find atom-text-editor[mini].is-focused .source .regexp, .find-and-replace atom-text-editor[mini].is-focused .source .regexp, .project-find atom-text-editor[mini].is-focused::shadow .source .regexp, .find-and-replace atom-text-editor[mini].is-focused::shadow .source .regexp` => `.project-find atom-text-editor[mini].is-focused .source .regexp, .find-and-replace atom-text-editor[mini].is-focused .source .regexp, .project-find atom-text-editor[mini].is-focused.editor .syntax--source .syntax--regexp, .find-and-replace atom-text-editor[mini].is-focused.editor .syntax--source .syntax--regexp`
* `atom-text-editor[mini], atom-text-editor[mini]::shadow` => `atom-text-editor[mini], atom-text-editor[mini].editor`
* `atom-text-editor[mini]:hover, atom-text-editor[mini]::shadow:hover` => `atom-text-editor[mini]:hover, atom-text-editor[mini].editor:hover`
* `atom-text-editor[mini] .text, atom-text-editor[mini]::shadow .text, atom-text-editor[mini] .source, atom-text-editor[mini]::shadow .source` => `atom-text-editor[mini] .text, atom-text-editor[mini].editor .syntax--text, atom-text-editor[mini] .source, atom-text-editor[mini].editor .syntax--source`
* `atom-text-editor[mini] .placeholder-text, atom-text-editor[mini]::shadow .placeholder-text` => `atom-text-editor[mini] .placeholder-text, atom-text-editor[mini].editor .placeholder-text`
* `atom-text-editor[mini] .cursor, atom-text-editor[mini]::shadow .cursor` => `atom-text-editor[mini] .cursor, atom-text-editor[mini].editor .cursor`
* `atom-text-editor[mini].is-focused, atom-text-editor[mini].is-focused::shadow` => `atom-text-editor[mini].is-focused, atom-text-editor[mini].is-focused.editor`
* `atom-text-editor[mini].is-focused .text, atom-text-editor[mini].is-focused::shadow .text, atom-text-editor[mini].is-focused .source, atom-text-editor[mini].is-focused::shadow .source` => `atom-text-editor[mini].is-focused .text, atom-text-editor[mini].is-focused.editor .syntax--text, atom-text-editor[mini].is-focused .source, atom-text-editor[mini].is-focused.editor .syntax--source`
* `atom-text-editor[mini].is-focused:hover, atom-text-editor[mini].is-focused::shadow:hover` => `atom-text-editor[mini].is-focused:hover, atom-text-editor[mini].is-focused.editor:hover`
* `atom-text-editor[mini].is-focused .selection .region, atom-text-editor[mini].is-focused::shadow .selection .region` => `atom-text-editor[mini].is-focused .selection .region, atom-text-editor[mini].is-focused.editor .selection .region`
* `atom-text-editor .scroll-view, atom-text-editor::shadow .scroll-view, :host .scroll-view` => `atom-text-editor .scroll-view, atom-text-editor.editor .scroll-view, :host .scroll-view`
* `atom-panel.modal atom-text-editor[mini], .overlay atom-text-editor[mini], atom-panel.modal atom-text-editor.mini, .overlay atom-text-editor.mini, atom-panel.modal atom-text-editor.mini::shadow, .overlay atom-text-editor.mini::shadow, atom-panel.modal atom-text-editor[mini]::shadow, .overlay atom-text-editor[mini]::shadow` => `atom-panel.modal atom-text-editor[mini], .overlay atom-text-editor[mini], atom-panel.modal atom-text-editor.mini, .overlay atom-text-editor.mini, atom-panel.modal atom-text-editor.mini.editor, .overlay atom-text-editor.mini.editor, atom-panel.modal atom-text-editor[mini].editor, .overlay atom-text-editor[mini].editor`
* `atom-panel.modal atom-text-editor[mini] .text, .overlay atom-text-editor[mini] .text, atom-panel.modal atom-text-editor.mini .text, .overlay atom-text-editor.mini .text, atom-panel.modal atom-text-editor.mini::shadow .text, .overlay atom-text-editor.mini::shadow .text, atom-panel.modal atom-text-editor[mini]::shadow .text, .overlay atom-text-editor[mini]::shadow .text` => `atom-panel.modal atom-text-editor[mini] .text, .overlay atom-text-editor[mini] .text, atom-panel.modal atom-text-editor.mini .text, .overlay atom-text-editor.mini .text, atom-panel.modal atom-text-editor.mini.editor .syntax--text, .overlay atom-text-editor.mini.editor .syntax--text, atom-panel.modal atom-text-editor[mini].editor .syntax--text, .overlay atom-text-editor[mini].editor .syntax--text`
* `atom-panel.modal atom-text-editor[mini].is-focused:hover, .overlay atom-text-editor[mini].is-focused:hover, atom-panel.modal atom-text-editor.mini.is-focused:hover, .overlay atom-text-editor.mini.is-focused:hover, atom-panel.modal atom-text-editor.mini::shadow.is-focused:hover, .overlay atom-text-editor.mini::shadow.is-focused:hover, atom-panel.modal atom-text-editor[mini]::shadow.is-focused:hover, .overlay atom-text-editor[mini]::shadow.is-focused:hover, atom-panel.modal atom-text-editor[mini]:hover, .overlay atom-text-editor[mini]:hover, atom-panel.modal atom-text-editor.mini:hover, .overlay atom-text-editor.mini:hover, atom-panel.modal atom-text-editor.mini::shadow:hover, .overlay atom-text-editor.mini::shadow:hover, atom-panel.modal atom-text-editor[mini]::shadow:hover, .overlay atom-text-editor[mini]::shadow:hover` => `atom-panel.modal atom-text-editor[mini].is-focused:hover, .overlay atom-text-editor[mini].is-focused:hover, atom-panel.modal atom-text-editor.mini.is-focused:hover, .overlay atom-text-editor.mini.is-focused:hover, atom-panel.modal atom-text-editor.mini.editor.is-focused:hover, .overlay atom-text-editor.mini.editor.is-focused:hover, atom-panel.modal atom-text-editor[mini].editor.is-focused:hover, .overlay atom-text-editor[mini].editor.is-focused:hover, atom-panel.modal atom-text-editor[mini]:hover, .overlay atom-text-editor[mini]:hover, atom-panel.modal atom-text-editor.mini:hover, .overlay atom-text-editor.mini:hover, atom-panel.modal atom-text-editor.mini.editor:hover, .overlay atom-text-editor.mini.editor:hover, atom-panel.modal atom-text-editor[mini].editor:hover, .overlay atom-text-editor[mini].editor:hover`
* `atom-text-editor atom-text-editor-minimap::shadow .minimap-visible-area, atom-text-editor::shadow atom-text-editor-minimap::shadow .minimap-visible-area, html atom-text-editor-minimap::shadow .minimap-visible-area` => `atom-text-editor atom-text-editor-minimap::shadow .minimap-visible-area, atom-text-editor.editor atom-text-editor-minimap::shadow .minimap-visible-area, html atom-text-editor-minimap::shadow .minimap-visible-area`
* `.markdown-preview[data-use-github-style] atom-text-editor, .markdown-preview[data-use-github-style] atom-text-editor::shadow` => `.markdown-preview[data-use-github-style] atom-text-editor, .markdown-preview[data-use-github-style] atom-text-editor.editor`
* `.markdown-preview[data-use-github-style] atom-text-editor .editor--private span.source, .markdown-preview[data-use-github-style] atom-text-editor::shadow .editor--private span.source` => `.markdown-preview[data-use-github-style] atom-text-editor .editor--private span.source, .markdown-preview[data-use-github-style] atom-text-editor.editor .editor--private span.syntax--source`
* `.markdown-preview[data-use-github-style] atom-text-editor, .markdown-preview[data-use-github-style] atom-text-editor::shadow, .markdown-preview[data-use-github-style] code` => `.markdown-preview[data-use-github-style] atom-text-editor, .markdown-preview[data-use-github-style] atom-text-editor.editor, .markdown-preview[data-use-github-style] code`
* `.markdown-preview atom-text-editor, .markdown-preview:not([data-use-github-style]) atom-text-editor, .markdown-preview atom-text-editor::shadow, .markdown-preview:not([data-use-github-style]) atom-text-editor::shadow` => `.markdown-preview atom-text-editor, .markdown-preview:not([data-use-github-style]) atom-text-editor, .markdown-preview atom-text-editor.editor, .markdown-preview:not([data-use-github-style]) atom-text-editor.editor`
* `.markdown-preview atom-text-editor .editor--private span.source, .markdown-preview:not([data-use-github-style]) atom-text-editor .editor--private span.source, .markdown-preview atom-text-editor::shadow .editor--private span.source, .markdown-preview:not([data-use-github-style]) atom-text-editor::shadow .editor--private span.source` => `.markdown-preview atom-text-editor .editor--private span.source, .markdown-preview:not([data-use-github-style]) atom-text-editor .editor--private span.source, .markdown-preview atom-text-editor.editor .editor--private span.syntax--source, .markdown-preview:not([data-use-github-style]) atom-text-editor.editor .editor--private span.syntax--source`
* `.markdown-preview atom-text-editor, .markdown-preview:not([data-use-github-style]) atom-text-editor, .markdown-preview atom-text-editor::shadow, .markdown-preview:not([data-use-github-style]) atom-text-editor::shadow, .markdown-preview code, .markdown-preview:not([data-use-github-style]) code` => `.markdown-preview atom-text-editor, .markdown-preview:not([data-use-github-style]) atom-text-editor, .markdown-preview atom-text-editor.editor, .markdown-preview:not([data-use-github-style]) atom-text-editor.editor, .markdown-preview code, .markdown-preview:not([data-use-github-style]) code`
* `.markdown-preview atom-text-editor[data-grammar="text plain"] .meta, .markdown-preview:not([data-use-github-style]) atom-text-editor[data-grammar="text plain"] .meta, .markdown-preview atom-text-editor[data-grammar="text plain"]::shadow .meta, .markdown-preview:not([data-use-github-style]) atom-text-editor[data-grammar="text plain"]::shadow .meta` => `.markdown-preview atom-text-editor[data-grammar="text plain"] .meta, .markdown-preview:not([data-use-github-style]) atom-text-editor[data-grammar="text plain"] .meta, .markdown-preview atom-text-editor[data-grammar="text plain"].editor .syntax--meta, .markdown-preview:not([data-use-github-style]) atom-text-editor[data-grammar="text plain"].editor .syntax--meta`
* `[theme-nord-atom-ui-form-focus-effect="nosnowlight"] .find-and-replace atom-text-editor[mini].is-focused, [theme-nord-atom-ui-form-focus-effect="nosnowlight"] .settings-view atom-text-editor[mini].is-focused, [theme-nord-atom-ui-form-focus-effect="nosnowlight"] .find-and-replace atom-text-editor[mini].is-focused::shadow, [theme-nord-atom-ui-form-focus-effect="nosnowlight"] .settings-view atom-text-editor[mini].is-focused::shadow` => `[theme-nord-atom-ui-form-focus-effect="nosnowlight"] .find-and-replace atom-text-editor[mini].is-focused, [theme-nord-atom-ui-form-focus-effect="nosnowlight"] .settings-view atom-text-editor[mini].is-focused, [theme-nord-atom-ui-form-focus-effect="nosnowlight"] .find-and-replace atom-text-editor[mini].is-focused.editor, [theme-nord-atom-ui-form-focus-effect="nosnowlight"] .settings-view atom-text-editor[mini].is-focused.editor`
* `[theme-nord-atom-ui-form-focus-effect="nosnowlight"] .find-and-replace atom-text-editor[mini].is-focused .text, [theme-nord-atom-ui-form-focus-effect="nosnowlight"] .settings-view atom-text-editor[mini].is-focused .text, [theme-nord-atom-ui-form-focus-effect="nosnowlight"] .find-and-replace atom-text-editor[mini].is-focused::shadow .text, [theme-nord-atom-ui-form-focus-effect="nosnowlight"] .settings-view atom-text-editor[mini].is-focused::shadow .text, [theme-nord-atom-ui-form-focus-effect="nosnowlight"] .find-and-replace atom-text-editor[mini].is-focused .source, [theme-nord-atom-ui-form-focus-effect="nosnowlight"] .settings-view atom-text-editor[mini].is-focused .source, [theme-nord-atom-ui-form-focus-effect="nosnowlight"] .find-and-replace atom-text-editor[mini].is-focused::shadow .source, [theme-nord-atom-ui-form-focus-effect="nosnowlight"] .settings-view atom-text-editor[mini].is-focused::shadow .source` => `[theme-nord-atom-ui-form-focus-effect="nosnowlight"] .find-and-replace atom-text-editor[mini].is-focused .text, [theme-nord-atom-ui-form-focus-effect="nosnowlight"] .settings-view atom-text-editor[mini].is-focused .text, [theme-nord-atom-ui-form-focus-effect="nosnowlight"] .find-and-replace atom-text-editor[mini].is-focused.editor .syntax--text, [theme-nord-atom-ui-form-focus-effect="nosnowlight"] .settings-view atom-text-editor[mini].is-focused.editor .syntax--text, [theme-nord-atom-ui-form-focus-effect="nosnowlight"] .find-and-replace atom-text-editor[mini].is-focused .source, [theme-nord-atom-ui-form-focus-effect="nosnowlight"] .settings-view atom-text-editor[mini].is-focused .source, [theme-nord-atom-ui-form-focus-effect="nosnowlight"] .find-and-replace atom-text-editor[mini].is-focused.editor .syntax--source, [theme-nord-atom-ui-form-focus-effect="nosnowlight"] .settings-view atom-text-editor[mini].is-focused.editor .syntax--source`
* `[theme-nord-atom-ui-form-focus-effect="nosnowlight"] .find-and-replace atom-text-editor[mini].is-focused .text .regexp, [theme-nord-atom-ui-form-focus-effect="nosnowlight"] .settings-view atom-text-editor[mini].is-focused .text .regexp, [theme-nord-atom-ui-form-focus-effect="nosnowlight"] .find-and-replace atom-text-editor[mini].is-focused::shadow .text .regexp, [theme-nord-atom-ui-form-focus-effect="nosnowlight"] .settings-view atom-text-editor[mini].is-focused::shadow .text .regexp, [theme-nord-atom-ui-form-focus-effect="nosnowlight"] .find-and-replace atom-text-editor[mini].is-focused .source .regexp, [theme-nord-atom-ui-form-focus-effect="nosnowlight"] .settings-view atom-text-editor[mini].is-focused .source .regexp, [theme-nord-atom-ui-form-focus-effect="nosnowlight"] .find-and-replace atom-text-editor[mini].is-focused::shadow .source .regexp, [theme-nord-atom-ui-form-focus-effect="nosnowlight"] .settings-view atom-text-editor[mini].is-focused::shadow .source .regexp` => `[theme-nord-atom-ui-form-focus-effect="nosnowlight"] .find-and-replace atom-text-editor[mini].is-focused .text .regexp, [theme-nord-atom-ui-form-focus-effect="nosnowlight"] .settings-view atom-text-editor[mini].is-focused .text .regexp, [theme-nord-atom-ui-form-focus-effect="nosnowlight"] .find-and-replace atom-text-editor[mini].is-focused.editor .syntax--text .syntax--regexp, [theme-nord-atom-ui-form-focus-effect="nosnowlight"] .settings-view atom-text-editor[mini].is-focused.editor .syntax--text .syntax--regexp, [theme-nord-atom-ui-form-focus-effect="nosnowlight"] .find-and-replace atom-text-editor[mini].is-focused .source .regexp, [theme-nord-atom-ui-form-focus-effect="nosnowlight"] .settings-view atom-text-editor[mini].is-focused .source .regexp, [theme-nord-atom-ui-form-focus-effect="nosnowlight"] .find-and-replace atom-text-editor[mini].is-focused.editor .syntax--source .syntax--regexp, [theme-nord-atom-ui-form-focus-effect="nosnowlight"] .settings-view atom-text-editor[mini].is-focused.editor .syntax--source .syntax--regexp`
* `[theme-nord-atom-ui-form-focus-effect="nosnowlight"] .find-and-replace atom-text-editor[mini].is-focused .highlights .region, [theme-nord-atom-ui-form-focus-effect="nosnowlight"] .settings-view atom-text-editor[mini].is-focused .highlights .region, [theme-nord-atom-ui-form-focus-effect="nosnowlight"] .find-and-replace atom-text-editor[mini].is-focused::shadow .highlights .region, [theme-nord-atom-ui-form-focus-effect="nosnowlight"] .settings-view atom-text-editor[mini].is-focused::shadow .highlights .region` => `[theme-nord-atom-ui-form-focus-effect="nosnowlight"] .find-and-replace atom-text-editor[mini].is-focused .highlights .region, [theme-nord-atom-ui-form-focus-effect="nosnowlight"] .settings-view atom-text-editor[mini].is-focused .highlights .region, [theme-nord-atom-ui-form-focus-effect="nosnowlight"] .find-and-replace atom-text-editor[mini].is-focused.editor .highlights .region, [theme-nord-atom-ui-form-focus-effect="nosnowlight"] .settings-view atom-text-editor[mini].is-focused.editor .highlights .region`
Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by arcticicestudio** [comment]
This is related to the change that [elements are no longer encapsulated within a shadow DOM boundary](http://blog.atom.io/2016/11/14/removing-shadow-dom-boundary-from-text-editor-elements.html) which is a theme package API change announced some weeks ago.
Atom will automatically convert the deprecated selectors so there should be no usage problems, the deprecation warning is only a preparation for package developers so they can update to the new API.

❕ Please subsribe to #49 with the associated [`improvement/ghi-#49-atom-1.13-shadow-dom-removal`](https://github.com/arcticicestudio/nord-atom-ui/tree/improvement/ghi-%2349-atom-1.13-shadow-dom-removal) branch which will be merged as soon as the versions of the official themes [One Dark UI](https://github.com/atom/one-dark-ui)  and [One Dark Syntax](https://github.com/atom/one-dark-syntax) are bumped to `<=1.13` in their `package.json` files to keep compability as long as lower versions are supported. ❕
