### ISSUE TITLE
Quick Open font color is unreadable

### ISSUE THREAD

**Issue by st-andrew** [arcticicestudio/nord-atom-ui#54]
After the most recent update of nord-atom-ui the Quick Open font color is too dark and is unreadable.  

![screenshot from 2017-01-25 14-39-21](https://cloud.githubusercontent.com/assets/8158705/22306418/35a308dc-e30d-11e6-8de9-cf503041625c.png)

Oddly enough, when the window is not focused the font color changes to what I assume is the regular color.

![screenshot from 2017-01-25 14-40-32](https://cloud.githubusercontent.com/assets/8158705/22306451/563f3d04-e30d-11e6-8522-42c1a0638d8a.png)

If you select the text that is typed you can see that it's there but it looks like it's a very dark shade of grey.

![screenshot from 2017-01-25 14-40-42](https://cloud.githubusercontent.com/assets/8158705/22306519/930df43c-e30d-11e6-91cb-dade232c489d.png)

Issue is not present in One Dark theme.

Atom    : 1.13.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
Fedora : 24

**Comment by arcticicestudio** [comment]
Thanks for your report 👍 
This has already been reported in #53 and has been fixed in the apm package release version 🏷 [0.10.1](https://github.com/arcticicestudio/nord-atom-ui/releases/tag/v0.10.1).
