### ISSUE TITLE
Color is off

### ISSUE THREAD

**Issue by rjventrone** [arcticicestudio/nord-atom-ui#63]
<img width="1439" alt="screen shot 2017-03-27 at 10 46 46 am" src="https://cloud.githubusercontent.com/assets/405316/24362463/dd39d27c-12da-11e7-9ff3-ba74f0fc9e45.png">

Sidebar folder color is yellow and text is green, should the folders be white and text white?

**Comment by st-andrew** [comment]
Those are contextual colours for Git to help show what's changed.  Green means those files/folders are new and yellow means they have been modified.  In your terminal run  `$ git status` from you project directory to see what I mean.

**Comment by rjventrone** [comment]
Thanks and sorry for issue first time using Atom. Great theme.
