### ISSUE TITLE
The selected file is unbolded

### ISSUE THREAD

**Issue by linjialiang** [arcticicestudio/nord-atom-ui#75]
> `Desired effect` : The currently selected file is bold

![default](https://user-images.githubusercontent.com/8848263/41133819-ad63cfc4-6afb-11e8-898a-fa82c685cc39.png)

---

> `at present`

![default](https://user-images.githubusercontent.com/8848263/41133895-1add4c06-6afc-11e8-8879-ac814f5de0c9.png)

**Comment by arcticicestudio** [comment]
The first screenshot shows another UI theme ([Nucleus Dark][ndui]) while the second one shows the [Northem Light Atom][nlaui], but this is the repository of the [Nord Atom UI][naui] theme. Please make sure to open a issue in the correct repository.

[ndui]: https://atom.io/themes/nucleus-dark-ui
[nlaui]: https://atom.io/themes/northem-light-atom-ui
[naui]: [nlaui]: https://atom.io/themes/nord-atom-ui
