### ISSUE TITLE
These places are not very beautifu

### ISSUE THREAD

**Issue by linjialiang** [arcticicestudio/nord-atom-ui#84]
> These places are not very beautifu：

![图片](https://user-images.githubusercontent.com/8848263/62467097-863b8a00-b7c5-11e9-83b7-7635ec9040d3.png)
![图片](https://user-images.githubusercontent.com/8848263/62467136-96ec0000-b7c5-11e9-8885-f0786164352e.png)

**Comment by linjialiang** [comment]
> Close the click effect of the button

```shell
cursor: pointer;
```

![图片](https://user-images.githubusercontent.com/8848263/62467544-9738cb00-b7c6-11e9-9df0-961ed6c416c8.png)

**Comment by arcticicestudio** [comment]
Duplicate of #67 

---

Hi @linjialiang :wave:, thanks for your contribution :+1:
This is a know problem already reported in #67. Unfortunately there are hundreds of other issues up in the queue so there was no time for that yet, but PRs are always welcome if someone likes to fix this.

**Comment by linjialiang** [comment]
> Why so many questions on one subject ?
